"""fix list relations

Revision ID: 7ebb390e6f8b
Revises: e2228c9d1e24
Create Date: 2024-02-11 00:26:29.568368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebb390e6f8b'
down_revision = 'e2228c9d1e24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
