"""vote_type field

Revision ID: e2228c9d1e24
Revises: 4a3049a61692
Create Date: 2023-01-15 05:27:46.186769

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

from src.utils_classes import VoteType


# revision identifiers, used by Alembic.
revision = "e2228c9d1e24"
down_revision = "4a3049a61692"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    vote_type = postgresql.ENUM(VoteType, name="votetype")
    vote_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "votes",
        sa.Column("vote_type", vote_type, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("votes", "vote_type")
    vote_type = postgresql.ENUM(VoteType, name="votetype")
    vote_type.drop(op.get_bind())
    # ### end Alembic commands ###
